### PR TITLE
MLLP extensions

### PR DESCRIPTION
**Pull request by Ravenheart**
I've added a very commonly used operation to the MessageHelper class, namely serializing messages/strings to MLLP encoded byte arrays.

### CODE REVIEW

**Comment by jaime-olivares** [comment]
I think MLLP is not a good name for those methods. It may be something like GetMLLP or GetMllpBuffer, to be similar to other existing methods.

**Comment by jaime-olivares** [comment]
Also, those static methods shall be part of the Message class (non-static)

**Comment by jaime-olivares** [comment]
I have done two modifications to your fork. It uses only two methods (rather than 4). One static at MessageHelper and one non-static to Message.
Let me know if you are ok for merging.

**Comment by Ravenheart** [comment]
Everything is OK to me.

**Comment by jaime-olivares** [comment]
Published as 2.16

**Pull request merged**
