### PR TITLE
Add support or .NET 4.5

### LINKED ISSUE #8: Add .NET 4.5 target
I know this is primarily targeting .NET standard, but there's nothing in here that limits it specifically to NetStandard1.3+. The library I'm building is targeting NetStandard2.0 AND Net45 so I would love if this would get pulled in. I've redone the tests to target everything as well.

### PR DESCRIPTION
**Pull request by kfrancis**
Fixes #8

### CODE REVIEW

**Comment by kfrancis** [comment]
If you do pull this, can you release a nuget update so I can pull this downstream?

**Comment by jaime-olivares** [comment]
Hi, you are adding more than described in the title. There are several 'tests' files that seem like duplicates. Please check.

**Comment by kfrancis** [comment]
Can do. I simply left your tests because they were in a netcore app as opposed to a test project.

**Comment by jaime-olivares** [comment]
Reverted, please try again without altering other files

**Pull request merged**
